name: PYTEST
on: [push]

jobs:
  test:
    name: Test against different Python versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8.x]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: setup python version
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - name: Install packages and run tests
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt       
        python -m pytest -vvv
      env:
        TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_service_providers
        POSTGRES_VER: 11
